name: Update Activity Graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate activity graph
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
            username: AleksaMilosevic07
            theme: github-dark
            bg_color: "0d1117"
            title_color: "58a6ff"
            color: "c9d1d9"
            line: "58a6ff"
            point: "1f6feb"
            output_path: dist/activity-graph.svg
      - name: Commit & Push SVG
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update activity graph"